default: &default
  adapter: postgresql
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: yardmaster
  password: yardmaster  

development:
  <<: *default
  database: yardmaster_development

test:
  <<: *default
  database: yardmaster_test

staging:
  <<: *default
  database: yardmaster_staging

production:
  <<: *default
  database: yardmaster_production

