# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2bc88c452b7421bc7328f74eeb810ac4f58d97e8ff9c9351cc1c7b662c1f14cac3654f215f9ced7e3f95fbbeb118d326e60b27fe4ad5c3bdf40093584e8390e

test:
  secret_key_base: d46996089453f0f1a53418fb73e7d33d930e8925c1a47e77d36fcab4a3b9855ae103593dd73529ce4008b58c27252bbdc1c24d2948aa866b3d5a4078494c2b48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
